routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::get('rekomendasiPengetahuan', 'RekomendasiPengetahuanController@index')->name('rekomendasiPengetahuan.index');
Route::prefix('rekomendasiPengetahuan')->group(function () {
    Route::get('peraturanPemerintah', 'RekomendasiPengetahuanController@peraturanPemerintah')->name('rekomendasiPengetahuan.peraturanPemerintah');
    Route::get('sumberPengetahuanBaru', 'RekomendasiPengetahuanController@sumberPengetahuanBaru')->name('rekomendasiPengetahuan.sumberPengetahuanBaru');
    Route::get('kasus', 'RekomendasiPengetahuanController@kasus')->name('rekomendasiPengetahuan.kasus');
    Route::get('experts', 'RekomendasiPengetahuanController@experts')->name('rekomendasiPengetahuan.experts');
});

Route::prefix('chat')->group(function () {
    Route::get('count', 'ChatSessionController@count');
    Route::post('start', 'ChatSessionController@start');
    Route::get('load/{id}', 'ChatSessionController@load');
    Route::post('send/{id}', 'ChatSessionController@send');
    Route::get('sync/{id}', 'ChatSessionController@sync');
});

Route::get('search', 'SearchController@index')->name('search.index');
Route::prefix('search')->group(function () {
    Route::get('kasus', 'SearchController@kasus');
    Route::get('pengetahuanOrganisasi', 'SearchController@pengetahuanOrganisasi');
    Route::get('peraturanPemerintah', 'SearchController@peraturanPemerintah');
    Route::get('sumberPengetahuanBaru', 'SearchController@sumberPengetahuanBaru');
});


Route::resource('tupoksiJabatan', 'TupoksiJabatanController');
Route::resource('pegawai', 'PegawaiController');
Route::resource('experts', 'ExpertController');
Route::resource('peraturanPemerintah', 'PeraturanPemerintahController');
Route::resource('pengetahuanOrganisasi', 'PengetahuanOrganisasiController');
Route::resource('knowledgeGaps', 'KnowledgeGapController');
Route::resource('kasus', 'KasusController');
Route::resource('sumberPengetahuanBaru', 'SumberPengetahuanBaruController');

app/Models/PeraturanPemerintah.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class PeraturanPemerintah
 * @package App\Models
 * @version November 17, 2017, 12:31 pm UTC
 *
 * @property tinyInteger jenis
 * @property string perihal
 * @property binary upload_dokumen
 * @property date tanggal
 */
class PeraturanPemerintah extends Model
{
    use SoftDeletes;

    public $table = 'peraturan_pemerintah';
    
    protected $dates = ['deleted_at'];


    public $fillable = [
        'jenis',
        'perihal',
        'upload_dokumen',
        'tanggal',
        'created_by',
        'updated_by',
        'pengetahuan_organisasi_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'perihal' => 'string',
        'tanggal' => 'date'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * Jenis Peraturan Pemerintah
     * 
     * @var array
     */
    const JENIS = [
        0 => 'LAIN-LAIN',
        1 => 'KEPMEN',
        2 => 'PERMEN',
        3 => 'KEPRES',
    ];

    /**
     * Get Pengetahuan Organisasi
     */
    public function pengetahuanOrganisasi()
    {
        return $this->belongsTo('App\Models\PengetahuanOrganisasi');
    }    

    /**
     * Set Jenis peraturan
     *
     * @param  string  $value
     * @return void
     */
    public function setJenisAttribute($value)
    {
        if (gettype($value) != 'integer') {
            try {
                $value = intval("$value");
            } catch (\Exception $e) {
                $value = 0;
            }
        }
        $this->attributes['jenis'] = $value;
    }    
}

app/Http/Controllers/PeraturanPemerintahController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePeraturanPemerintahRequest;
use App\Http\Requests\UpdatePeraturanPemerintahRequest;
use App\Repositories\PeraturanPemerintahRepository;
use App\Repositories\PengetahuanOrganisasiRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class PeraturanPemerintahController extends AppBaseController
{
    /** @var  PeraturanPemerintahRepository */
    private $peraturanPemerintahRepository;

    /** @var  PengetahuanOrganisasiRepository */
    private $pengetahuanOrganisasiRepository;

    private $dateFormat = 'd/m/Y';

    public function __construct(PeraturanPemerintahRepository $peraturanPemerintahRepo, PengetahuanOrganisasiRepository $pengetahuanOrganisasiRepository)
    {
        $this->middleware('auth');
        $this->peraturanPemerintahRepository = $peraturanPemerintahRepo;
        $this->pengetahuanOrganisasiRepository = $pengetahuanOrganisasiRepository;
    }

    /**
     * Display a listing of the PeraturanPemerintah.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->peraturanPemerintahRepository->pushCriteria(new RequestCriteria($request));
        $peraturanPemerintah = $this->peraturanPemerintahRepository->all();

        return view('peraturan_pemerintah.index')
            ->with('peraturanPemerintah', $peraturanPemerintah)
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Show the form for creating a new PeraturanPemerintah.
     *
     * @return Response
     */
    public function create()
    {
        $pengetahuanList = $this->pengetahuanOrganisasiRepository->pluck('nama_pengetahuan', 'id')->all();
        return view('peraturan_pemerintah.create')
            ->with('pengetahuanList', $pengetahuanList)
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Store a newly created PeraturanPemerintah in storage.
     *
     * @param CreatePeraturanPemerintahRequest $request
     *
     * @return Response
     */
    public function store(CreatePeraturanPemerintahRequest $request)
    {
        $input = $request->all();
        $input['tanggal'] = \Carbon\Carbon::createFromFormat($this->dateFormat, $input['tanggal']);
        $input['created_by'] = \Auth::user()->username;

        // replace with binary
        if ($request->hasFile('upload_dokumen')) {
            $path = $request->file('upload_dokumen')->path();
            $input['upload_dokumen'] = file_get_contents($path);
        }

        $peraturanPemerintah = $this->peraturanPemerintahRepository->create($input);
        Flash::success('Peraturan Pemerintah saved successfully.');
        return redirect(route('peraturanPemerintah.index'));
    }

    /**
     * Display the specified PeraturanPemerintah.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $peraturanPemerintah = $this->peraturanPemerintahRepository->with('pengetahuanOrganisasi')->findWithoutFail($id);

        if (empty($peraturanPemerintah)) {
            Flash::error('Peraturan Pemerintah not found');
            return redirect(route('peraturanPemerintah.index'));
        }

        return view('peraturan_pemerintah.show')->with('peraturanPemerintah', $peraturanPemerintah)->with('dateFormat', $this->dateFormat);
    }

    /**
     * Show the form for editing the specified PeraturanPemerintah.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $peraturanPemerintah = $this->peraturanPemerintahRepository->findWithoutFail($id);

        if (empty($peraturanPemerintah)) {
            Flash::error('Peraturan Pemerintah not found');
            return redirect(route('peraturanPemerintah.index'));
        }

        $pengetahuanList = $this->pengetahuanOrganisasiRepository->pluck('nama_pengetahuan', 'id')->all();

        return view('peraturan_pemerintah.edit')
            ->with('peraturanPemerintah', $peraturanPemerintah)
            ->with('pengetahuanList', $pengetahuanList)
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Update the specified PeraturanPemerintah in storage.
     *
     * @param  int              $id
     * @param UpdatePeraturanPemerintahRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePeraturanPemerintahRequest $request)
    {
        $peraturanPemerintah = $this->peraturanPemerintahRepository->findWithoutFail($id);

        if (empty($peraturanPemerintah)) {
            Flash::error('Peraturan Pemerintah not found');
            return redirect(route('peraturanPemerintah.index'));
        }

        $input = $request->all();        
        $input['tanggal'] = \Carbon\Carbon::createFromFormat($this->dateFormat, $input['tanggal']);
        $input['updated_by'] = \Auth::user()->username;

        // replace with binary
        if ($request->hasFile('upload_dokumen')) {
            $path = $request->file('upload_dokumen')->path();
            $input['upload_dokumen'] = file_get_contents($path);
        }
        
        $peraturanPemerintah = $this->peraturanPemerintahRepository->update($input, $id);
        Flash::success('Peraturan Pemerintah updated successfully.');
        return redirect(route('peraturanPemerintah.index'));
    }

    /**
     * Remove the specified PeraturanPemerintah from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $peraturanPemerintah = $this->peraturanPemerintahRepository->findWithoutFail($id);

        if (empty($peraturanPemerintah)) {
            Flash::error('Peraturan Pemerintah not found');

            return redirect(route('peraturanPemerintah.index'));
        }

        $this->peraturanPemerintahRepository->delete($id);

        Flash::success('Peraturan Pemerintah deleted successfully.');

        return redirect(route('peraturanPemerintah.index'));
    }
}

resources/views/peraturan_pemerintah/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Peraturan Pemerintah
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'peraturanPemerintah.store', 'enctype' => 'multipart/form-data']) !!}

                        @include('peraturan_pemerintah.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/peraturan_pemerintah/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Peraturan Pemerintah
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($peraturanPemerintah, ['route' => ['peraturanPemerintah.update', $peraturanPemerintah->id, 'enctype' => 'multipart/form-data'], 'method' => 'patch']) !!}

                        @include('peraturan_pemerintah.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/peraturan_pemerintah/fields.blade.php
<!-- Jenis Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jenis', 'Jenis:') !!}
    {!! Form::select('jenis', \App\Models\PeraturanPemerintah::JENIS, null, ['class' => 'form-control']) !!}
</div>

<!-- Pengetahuan Organisasi Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pengetahuan_organisasi_id', 'Pengetahuan Organisasi:') !!}
    {!! Form::select('pengetahuan_organisasi_id', $pengetahuanList, null, ['class' => 'form-control', 'placeholder' => 'Please Select..']) !!}
</div>

<!-- Perihal Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('perihal', 'Perihal:') !!}
    {!! Form::textarea('perihal', null, ['class' => 'form-control']) !!}
</div>

<!-- Upload Dokumen Field -->
<div class="form-group col-sm-6">
    {!! Form::label('upload_dokumen', 'Upload Dokumen:') !!}
    {!! Form::file('upload_dokumen') !!}
    @if (!empty($peraturanPemerintah) && !empty($peraturanPemerintah->upload_dokumen))
    <p><embed src="data:application/pdf;base64,{!! base64_encode($peraturanPemerintah->upload_dokumen) !!}" width="500" height="375" type='application/pdf'></p>
    @endif
</div>
<div class="clearfix"></div>

<!-- Tanggal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tanggal', 'Tanggal:') !!}
    {!! Form::datePicker('tanggal', empty($peraturanPemerintah) ? null : $peraturanPemerintah->tanggal->format($dateFormat), ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('peraturanPemerintah.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/peraturan_pemerintah/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Peraturan Pemerintah</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('peraturanPemerintah.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('peraturan_pemerintah.table')
            </div>
        </div>
    </div>
@endsection

resources/views/peraturan_pemerintah/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Peraturan Pemerintah
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('peraturan_pemerintah.show_fields')
                    <a href="{!! route('peraturanPemerintah.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/peraturan_pemerintah/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $peraturanPemerintah->id !!}</p>
</div>

<!-- Jenis Field -->
<div class="form-group">
    {!! Form::label('jenis', 'Jenis:') !!}
    <p>{!! \App\Models\PeraturanPemerintah::JENIS[$peraturanPemerintah->jenis] !!}</p>
</div>

<!-- Pengetahuan Organisasi Field -->
<div class="form-group">
    {!! Form::label('pengetahuan_organisasi_id', 'Pengetahuan Organisasi:') !!}
    <p>{!! $peraturanPemerintah->pengetahuanOrganisasi->nama_pengetahuan !!}</p>
</div>

<!-- Perihal Field -->
<div class="form-group">
    {!! Form::label('perihal', 'Perihal:') !!}
    <p>{!! $peraturanPemerintah->perihal !!}</p>
</div>

<!-- Upload Dokumen Field -->
<div class="form-group">
    {!! Form::label('upload_dokumen', 'Upload Dokumen:') !!}
    @if (!empty($peraturanPemerintah) && !empty($peraturanPemerintah->upload_dokumen))
    <p><embed src="data:application/pdf;base64,{!! base64_encode($peraturanPemerintah->upload_dokumen) !!}" width="500" height="375" type='application/pdf'></p>
    @endif
</div>

<!-- Tanggal Field -->
<div class="form-group">
    {!! Form::label('tanggal', 'Tanggal:') !!}
    <p>{!! $peraturanPemerintah->tanggal !!}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created By:') !!}
    <p>{!! $peraturanPemerintah->created_by !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $peraturanPemerintah->created_at !!}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{!! $peraturanPemerintah->updated_by !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $peraturanPemerintah->updated_at !!}</p>
</div>

resources/views/peraturan_pemerintah/table.blade.php
<table class="table table-responsive" id="peraturanPemerintah-table">
    <thead>
        <tr>
            <th>Perihal</th>
            <th>Jenis</th>
            <th>Tanggal</th>
            <th>Created By</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($peraturanPemerintah as $peraturanPemerintah)
        <tr>
            <td>{!! str_limit($peraturanPemerintah->perihal, 50) !!}</td>
            <td>{!! \App\Models\PeraturanPemerintah::JENIS[$peraturanPemerintah->jenis] !!}</td>
            <td>{!! $peraturanPemerintah->tanggal->format($dateFormat) !!}</td>
            <td>{!! $peraturanPemerintah->created_by !!}</td>
            <td>
                {!! Form::open(['route' => ['peraturanPemerintah.destroy', $peraturanPemerintah->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('peraturanPemerintah.show', [$peraturanPemerintah->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('peraturanPemerintah.edit', [$peraturanPemerintah->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>