routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::get('rekomendasiPengetahuan', 'RekomendasiPengetahuanController@index')->name('rekomendasiPengetahuan.index');
Route::prefix('rekomendasiPengetahuan')->group(function () {
    Route::get('peraturanPemerintah', 'RekomendasiPengetahuanController@peraturanPemerintah')->name('rekomendasiPengetahuan.peraturanPemerintah');
    Route::get('sumberPengetahuanBaru', 'RekomendasiPengetahuanController@sumberPengetahuanBaru')->name('rekomendasiPengetahuan.sumberPengetahuanBaru');
    Route::get('kasus', 'RekomendasiPengetahuanController@kasus')->name('rekomendasiPengetahuan.kasus');
    Route::get('experts', 'RekomendasiPengetahuanController@experts')->name('rekomendasiPengetahuan.experts');
});

Route::prefix('chat')->group(function () {
    Route::get('count', 'ChatSessionController@count');
    Route::post('start', 'ChatSessionController@start');
    Route::get('load/{id}', 'ChatSessionController@load');
    Route::post('send/{id}', 'ChatSessionController@send');
    Route::get('sync/{id}', 'ChatSessionController@sync');
});

Route::get('search', 'SearchController@index')->name('search.index');
Route::prefix('search')->group(function () {
    Route::get('kasus', 'SearchController@kasus');
    Route::get('pengetahuanOrganisasi', 'SearchController@pengetahuanOrganisasi');
    Route::get('peraturanPemerintah', 'SearchController@peraturanPemerintah');
    Route::get('sumberPengetahuanBaru', 'SearchController@sumberPengetahuanBaru');
});


Route::resource('tupoksiJabatan', 'TupoksiJabatanController');
Route::resource('pegawai', 'PegawaiController');
Route::resource('experts', 'ExpertController');
Route::resource('peraturanPemerintah', 'PeraturanPemerintahController');
Route::resource('pengetahuanOrganisasi', 'PengetahuanOrganisasiController');
Route::resource('knowledgeGaps', 'KnowledgeGapController');
Route::resource('kasus', 'KasusController');
Route::resource('sumberPengetahuanBaru', 'SumberPengetahuanBaruController');

app/Models/PengetahuanOrganisasi.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class PengetahuanOrganisasi
 * @package App\Models
 * @version November 17, 2017, 12:53 pm UTC
 *
 * @property string nama_pengetahuan
 * @property string deskripsi_pengetahuan
 * @property binary upload_dokumen
 * @property date tanggal
 */
class PengetahuanOrganisasi extends Model
{
    use SoftDeletes;

    public $table = 'pengetahuan_organisasi';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nama_pengetahuan',
        'deskripsi_pengetahuan',
        'upload_dokumen',
        'tanggal',
        'created_by',
        'updated_by'        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nama_pengetahuan' => 'string',
        'deskripsi_pengetahuan' => 'string',
        'tanggal' => 'date'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama_pengetahuan' => 'required',
    ];


    /**
     * Get Experts
     */
    public function experts()
    {
        return $this->hasMany('App\Models\Expert');
    }    

    /**
     * Get Peraturan Pemerintah
     */
    public function peraturanPemerintah()
    {
        return $this->hasMany('App\Models\PeraturanPemerintah');
    }    

    /**
     * Get Knowlege Gaps
     */
    public function knowledgeGaps()
    {
        return $this->hasMany('App\Models\KnowledgeGap');
    }    

    /**
     * Get Sumber Pengetahuan Baru
     */
    public function sumberPengetahuanBaru()
    {
        return $this->hasMany('App\Models\SumberPengetahuanBaru');
    }    

    /**
     * Get Knowlege Kasus
     */
    public function kasus()
    {
        return $this->hasMany('App\Models\Kasus');
    }    
    
}

app/Http/Controllers/PengetahuanOrganisasiController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePengetahuanOrganisasiRequest;
use App\Http\Requests\UpdatePengetahuanOrganisasiRequest;
use App\Repositories\PengetahuanOrganisasiRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class PengetahuanOrganisasiController extends AppBaseController
{
    /** @var  PengetahuanOrganisasiRepository */
    private $pengetahuanOrganisasiRepository;

    private $dateFormat = 'd/m/Y';

    public function __construct(PengetahuanOrganisasiRepository $pengetahuanOrganisasiRepo)
    {
        $this->middleware('auth');
        $this->pengetahuanOrganisasiRepository = $pengetahuanOrganisasiRepo;
    }

    /**
     * Display a listing of the PengetahuanOrganisasi.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->pengetahuanOrganisasiRepository->pushCriteria(new RequestCriteria($request));
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->all();

        return view('pengetahuan_organisasi.index')
            ->with('pengetahuanOrganisasi', $pengetahuanOrganisasi)
            ->with('dateFormat', $this->dateFormat);;
    }

    /**
     * Show the form for creating a new PengetahuanOrganisasi.
     *
     * @return Response
     */
    public function create()
    {
        return view('pengetahuan_organisasi.create')
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Store a newly created PengetahuanOrganisasi in storage.
     *
     * @param CreatePengetahuanOrganisasiRequest $request
     *
     * @return Response
     */
    public function store(CreatePengetahuanOrganisasiRequest $request)
    {
        $input = $request->all();
        $input['tanggal'] = \Carbon\Carbon::createFromFormat($this->dateFormat, $input['tanggal']);
        $input['created_by'] = \Auth::user()->username;

        // replace with binary
        if ($request->hasFile('upload_dokumen')) {
            $path = $request->file('upload_dokumen')->path();
            $input['upload_dokumen'] = file_get_contents($path);
        }

        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->create($input);
        Flash::success('Pengetahuan Organisasi saved successfully.');
        return redirect(route('pengetahuanOrganisasi.index'));
    }

    /**
     * Display the specified PengetahuanOrganisasi.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->findWithoutFail($id);

        if (empty($pengetahuanOrganisasi)) {
            Flash::error('Pengetahuan Organisasi not found');

            return redirect(route('pengetahuanOrganisasi.index'));
        }

        return view('pengetahuan_organisasi.show')
            ->with('pengetahuanOrganisasi', $pengetahuanOrganisasi)
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Show the form for editing the specified PengetahuanOrganisasi.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->findWithoutFail($id);

        if (empty($pengetahuanOrganisasi)) {
            Flash::error('Pengetahuan Organisasi not found');

            return redirect(route('pengetahuanOrganisasi.index'));
        }

        return view('pengetahuan_organisasi.edit')
            ->with('pengetahuanOrganisasi', $pengetahuanOrganisasi)
            ->with('dateFormat', $this->dateFormat);
    }

    /**
     * Update the specified PengetahuanOrganisasi in storage.
     *
     * @param  int              $id
     * @param UpdatePengetahuanOrganisasiRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePengetahuanOrganisasiRequest $request)
    {
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->findWithoutFail($id);

        if (empty($pengetahuanOrganisasi)) {
            Flash::error('Pengetahuan Organisasi not found');
            return redirect(route('pengetahuanOrganisasi.index'));
        }

        $input = $request->all();        
        $input['tanggal'] = \Carbon\Carbon::createFromFormat($this->dateFormat, $input['tanggal']);
        $input['updated_by'] = \Auth::user()->username;

        // replace with binary
        if ($request->hasFile('upload_dokumen')) {
            $path = $request->file('upload_dokumen')->path();
            $input['upload_dokumen'] = file_get_contents($path);
        }
        
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->update($input, $id);
        Flash::success('Pengetahuan Organisasi updated successfully.');
        return redirect(route('pengetahuanOrganisasi.index'));
    }

    /**
     * Remove the specified PengetahuanOrganisasi from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $pengetahuanOrganisasi = $this->pengetahuanOrganisasiRepository->findWithoutFail($id);

        if (empty($pengetahuanOrganisasi)) {
            Flash::error('Pengetahuan Organisasi not found');

            return redirect(route('pengetahuanOrganisasi.index'));
        }

        $this->pengetahuanOrganisasiRepository->delete($id);

        Flash::success('Pengetahuan Organisasi deleted successfully.');

        return redirect(route('pengetahuanOrganisasi.index'));
    }
}

resources/views/pengetahuan_organisasi/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pengetahuan Organisasi
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'pengetahuanOrganisasi.store', 'enctype' => 'multipart/form-data']) !!}

                        @include('pengetahuan_organisasi.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pengetahuan_organisasi/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pengetahuan Organisasi
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($pengetahuanOrganisasi, ['route' => ['pengetahuanOrganisasi.update', $pengetahuanOrganisasi->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                        @include('pengetahuan_organisasi.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/pengetahuan_organisasi/fields.blade.php
<!-- Nama Pengetahuan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_pengetahuan', 'Nama Pengetahuan:') !!}
    {!! Form::text('nama_pengetahuan', null, ['class' => 'form-control']) !!}
</div>

<!-- Deskripsi Pengetahuan Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('deskripsi_pengetahuan', 'Deskripsi Pengetahuan:') !!}
    {!! Form::textarea('deskripsi_pengetahuan', null, ['class' => 'form-control']) !!}
</div>

<!-- Upload Dokumen Field -->
<div class="form-group col-sm-6">
    {!! Form::label('upload_dokumen', 'Upload Dokumen:') !!}
    {!! Form::file('upload_dokumen') !!}
    @if (!empty($pengetahuanOrganisasi) && !empty($pengetahuanOrganisasi->upload_dokumen))
    <p><embed src="data:application/pdf;base64,{!! base64_encode($pengetahuanOrganisasi->upload_dokumen) !!}" width="500" height="375" type='application/pdf'></p>
    @endif
</div>
<div class="clearfix"></div>

<!-- Tanggal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tanggal', 'Tanggal:') !!}
    {!! Form::datePicker('tanggal', empty($pengetahuanOrganisasi) ? null : $pengetahuanOrganisasi->tanggal->format($dateFormat), ['class' => 'form-control']) !!}    
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('pengetahuanOrganisasi.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/pengetahuan_organisasi/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Pengetahuan Organisasi</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('pengetahuanOrganisasi.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('pengetahuan_organisasi.table')
            </div>
        </div>
    </div>
@endsection

resources/views/pengetahuan_organisasi/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pengetahuan Organisasi
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('pengetahuan_organisasi.show_fields')
                    <a href="{!! route('pengetahuanOrganisasi.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pengetahuan_organisasi/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $pengetahuanOrganisasi->id !!}</p>
</div>

<!-- Nama Pengetahuan Field -->
<div class="form-group">
    {!! Form::label('nama_pengetahuan', 'Nama Pengetahuan:') !!}
    <p>{!! $pengetahuanOrganisasi->nama_pengetahuan !!}</p>
</div>

<!-- Deskripsi Pengetahuan Field -->
<div class="form-group">
    {!! Form::label('deskripsi_pengetahuan', 'Deskripsi Pengetahuan:') !!}
    <p>{!! $pengetahuanOrganisasi->deskripsi_pengetahuan !!}</p>
</div>

<!-- Upload Dokumen Field -->
<div class="form-group">
    {!! Form::label('upload_dokumen', 'Upload Dokumen:') !!}
    @if (!empty($pengetahuanOrganisasi) && !empty($pengetahuanOrganisasi->upload_dokumen))
    <p><embed src="data:application/pdf;base64,{!! base64_encode($pengetahuanOrganisasi->upload_dokumen) !!}" width="500" height="375" type='application/pdf'></p>
    @endif
</div>


<!-- Tanggal Field -->
<div class="form-group">
    {!! Form::label('tanggal', 'Tanggal:') !!}
    <p>{!! $pengetahuanOrganisasi->tanggal !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $pengetahuanOrganisasi->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $pengetahuanOrganisasi->updated_at !!}</p>
</div>

resources/views/pengetahuan_organisasi/table.blade.php
<table class="table table-responsive" id="pengetahuanOrganisasi-table">
    <thead>
        <tr>
            <th>Nama Pengetahuan</th>
            <th>Tanggal</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($pengetahuanOrganisasi as $pengetahuanOrganisasi)
        <tr>
            <td>{!! $pengetahuanOrganisasi->nama_pengetahuan !!}</td>
            <td>{!! $pengetahuanOrganisasi->tanggal->format($dateFormat) !!}</td>
            <td>
                {!! Form::open(['route' => ['pengetahuanOrganisasi.destroy', $pengetahuanOrganisasi->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('pengetahuanOrganisasi.show', [$pengetahuanOrganisasi->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('pengetahuanOrganisasi.edit', [$pengetahuanOrganisasi->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>